### ISSUE TITLE
Integration tests failing because of changed data

### ISSUE THREAD

**Issue by villasv** [VigilantePolitico/vigilante#28]
Flavio Bolsonaro updated his Facebook link.

**Comment by villasv** [comment]
Will be patched in the next PR, probably #27 .

**Comment by villasv** [comment]
Done.

**Comment by villasv** [comment]
Once again, someone changed data. #18 should be addressed ASAP

**Comment by Coqueiro** [comment]
To be closed with #33. Just reinforcing, #18 needs attention. This kind of constant bugfixing deprecates the project.
