### ISSUE TITLE
Add a PostgreSQL pipeline to persist Alderman items

### ISSUE THREAD

**Issue by villasv** [VigilantePolitico/vigilante#5]
This should be a high priority pipeline. Handling upserts is probably the easiest way to avoid reseting the database.

**Comment by Coqueiro** [comment]
Where are we going to host this database? Or are we working with local configs? We should keep this in perspective.

**Comment by villasv** [comment]
Heroku provides PostgreSQL as built-in add-on, which is fine for us. It's actually already created and it automatically configures environment variables, so all we have to do is connect to `DATABASE_URL`.

**Comment by villasv** [comment]
Closed by merging #10
